version: '3.8'

services:
  db:
    image: postgres:16.2-alpine3.19
    container_name: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '${POSTGRES_PORT}:5432'
    restart: always
    env_file:
      - .env
    hostname: ${POSTGRES_DB}
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}", "-h", "localhost"]
      timeout: 10s
      retries: 5

volumes:
  postgres_data: