# Generated by Django 4.2 on 2023-04-30 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Smoking',
            field=models.CharField(blank=True, choices=[('Neut', 'Neutral'), ('Neg', 'Negative'), ('Pos', 'Positive')], default=('Neut', 'Neutral'), max_length=256, null=True),
        ),
    ]
