# Generated by Django 4.2 on 2023-04-30 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_user_smoking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Smoking',
            field=models.CharField(blank=True, choices=[('Neut', 'Neutral'), ('Neg', 'Negative'), ('Pos', 'Positive')], max_length=256, null=True),
        ),
    ]
