# Generated by Django 4.2 on 2023-05-02 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_message_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['CreatedAt']},
        ),
    ]
